#!/bin/bash
curdir=$(dirname $0)
cryptolist_address="$curdir""/Dependencies/cryptolist-filtered"
linenumber=1
while $found != "yes"
do
find_name=$(cat $cryptolist_address | head -$linenumber | tail -1)
#If the filtered variable $findname has $crypto_name (which is from the main CryptoAlert executable) then fetch id
if $(echo $find_name | grep $crypto_name) != ""
then
found="yes"
idplace=$(expr "$linenumber"-1)
crypto_name=$(cat $cryptolist_address | sed s/\"//g | sed s/i// | sed s/d// | sed s/,// | sed s/://) " #removes characters " i d , and : and updates variable crypto_name (in main CryptoAlert executable)
echo "The id is ""$crypto_name"
else
find_name=$(expr "$find_name"+1)
fi
done
