#!/bin/sh
#This is CryptoAlert. It gives you the info of cryptocurrencies. Look at README.md for info
#Defining repeating functions (repeats if input not in correct format)
#This asks whether the user has a Coinmarketcap API ID
function is_api_present {
read -sn1 api_id_input
case $api_id_input in
y) api_id_presence=yes ;;
n) api_id_presence=no ;;
*) clear; echo "Your input was neither y or n. Please try again"; api_id_ask ;;
esac
}
#This asks for the plan the user has (if user does have one). Please Add later
#function what_api_plan {
#read api_plan
#}
function is_save_key {
read -n1 -p "Would you like CryptoAlert to save you Coinmarketcap API Key? (y/n)" save_key
case $save_key in
y) touch $(dirname $0)/Key; echo $apiKey > $(dirname $0)/Key ;;
n) ;;
*) echo "You didn't input y or n, try again"; is_save_key ;;
esac
}
#Code starts here
echo "Do you have a Coinmarketcap API Key? (y/n)"
is_api_present
clear
if $api_id_presence="no"
then
echo "Open https://coinmarketcap.com/api/pricing/ (right-click the link and click Open URL) and choose the plan of your choice"
else
#Later, add max checks/hr based on plan
echo "Paste your API Key from Coinmarketcap"
read -s apiKey
clear
cat << eol
There are different ways to input data for fetching in CryptoAlert. There is:
The ID (1 for Bitcoin, 2 for Litecoin etc.)
The symbol (BTC for Bitcoin, ETH for Ethereum)
The slug (bitcoin for Bitcoin, ethereum for Ethereum)
IMPORTANT: The slug MUST be lowercase at ALL TIMES
eol
read -p "What cryptocurrency do you want to view? ~" crypto_name
clear
read -p "Did you use an ID, a symbol, or a slug? ~" input_type
curl -H "X-CMC_PRO_API_KEY:  $apiKey" -H "Accept: application/json" -G https://sandbox-api.coinmarketcap.com/v1/cryptocurrency/quotes/latest?$input_type=$crypto_name | grep "price\|market_cap\|percent_change_1h\|percent_change_24h\|percent_change_7d"

fi
#if ! (-e $(dirname $0)/Key)
#then
#is_save_key
#fi
#end

