#!/bin/bash
curdir=$(dirname $0)
cryptolist_address="$curdir""/Dependencies/cryptolist-filtered"
linenumber=1
while $found != "yes"
do
find_name=$(cat $cryptolist_address | head -$linenumber | tail -1)
#If the filtered variable $findname has $crypto_name (which is from the main CryptoAlert executable) then fetch id
if $(echo $findname | grep $crypto_name) == $crypto_name
then
found="yes"
idplace=$(expr "$linenumber"+1)
cat $cryptolist_address | head -"$idplace"
